labs14-brav/Frontend

client/package-lock.json
client/package.json
client/src/App.css
client/src/App.js

Added axios and did a .get to /users endpoint on production deployment. Mapped through the users just to show data is displaying properly from backend.

Database data display

---

client/package-lock.json
client/package.json
client/src/App.js
client/src/auth_config.json
client/src/components/navBar.js
client/src/index.js
client/src/react-auth0-wrapper.js

Authorization

---

client/src/App.js

One line fix for production branch .get URL

Fixed production branch

---

client/package-lock.json
client/package.json
client/src/helpers/index.js
client/src/helpers/mixpanel.js
client/src/views/Landing.js

Install and setup mixpanel for user analytics.

Add mixpanel

---

client/package-lock.json
client/package.json
client/src/views/Auth0Callback.js

setup react-loader-spinner on callback

---

client/package-lock.json
client/src/routes/helpers/PrivateRoute.js
client/src/views/Home.js
client/src/views/Landing.js
client/src/views/Login.js
netlify.toml

Brought in Firebase 
- [x ] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [x ] I have added tests that prove my fix is effective or that my feature works AND the tests pass

Secure private route

---

client/src/routes/helpers/PrivateRoute.js
client/src/views/Home.js

urls are dynamic for exsisting requests

---

.gitignore
client/package-lock.json
client/package.json
client/public/index.html
client/src/routes/UsersRouter.js
client/src/routes/helpers/PrivateRoute.js
client/src/views/MediatorRegistration.js
client/src/views/Settings.js
client/src/views/index.js

Mediator request

---

client/.env
client/.gitignore
client/package-lock.json
client/package.json
client/src/App.js
client/src/components/MediatorCard.js
client/src/components/MediatorList.js
client/src/components/index.js
client/src/helpers/axioswithAuth.js
client/src/helpers/index.js
client/src/routes/CasesRouter.js
client/src/routes/TestRouter.js
client/src/routes/helpers/PrivateRoute.js
client/src/routes/index.js
client/src/views/CaseShow.js
client/src/views/Home.js
client/src/views/Search.js
client/src/views/index.js

Added a basic search for mediators. Added a search view, MediatorList/Card components, and Case view for a router link. 

Mediator search FE

---

client/src/components/MediatorCard.js
client/src/components/UserCaseCard.js
client/src/components/UserCaseCard.scss
client/src/components/UserCaseList.js
client/src/components/index.js
client/src/routes/CasesRouter.js
client/src/views/UserCaseShow.js
client/src/views/index.js

Added `UserCaseShow` view for users, which renders `UserCaseList`. Created modal for adding addendums to cases, using the endpoint `/cases/:id/addendums`. General case view for `User` type users.

User case management

---

client/src/components/AdminMediatorRequestList.js
client/src/components/index.js
client/src/routes/RootRouter.js
client/src/routes/UsersRouter.js
client/src/routes/helpers/PrivateRoute.js
client/src/views/AdminHome.js
client/src/views/MediatorRegistration.js
client/src/views/index.js

Created a view for admin only and pulled mediator requests from backend into component in view. Added two put methods in order to accept and decline request.
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas

Admin approval of mediator

---

client/package-lock.json
client/src/components/AdminMediatorRequestList.js
client/src/components/MediatorAcceptedCaseList.js
client/src/components/MediatorCompletedCaseList.js
client/src/components/MediatorPendingCaseList.js

Changed endpoints in order to receive the mediator id from local storage to send to backend.
- [x ] I have performed a self-review of my own code

Changed endpoints for mediator pending, active and completed lists

---

client/src/components/MediatorCard.js
client/src/components/MediatorFilter.js
client/src/components/MediatorList.js

Fixed MediatorList useEffect so it re-renders mediators after the filter has changed. Also added a price to the mediatorCard component.

Quick fix for Mediator Filter

---

client/src/components/MediatorFilter.js
client/src/components/MediatorList.js

Quick fix for specialization to match Back-End

Quick specialization hotfix

---

client/src/components/MediatorCard.js
client/src/components/SendRequestButton.js

Send request button

---

client/src/App.js
client/src/components/AdminMediatorRequestList.js
client/src/components/CourtForm.js
client/src/components/DeactivateAccountButton.js
client/src/components/MediatorCard.js
client/src/components/MediatorFilter.js
client/src/components/MediatorList.js
client/src/components/NavBar.js
client/src/components/OutsideCourtForm.js
client/src/components/SendRequestButton.js
client/src/components/UserCaseCard.js
client/src/components/UserCaseList.js
client/src/components/modals/AreYouSureDialog.js
client/src/components/modals/SimpleDialog.js
client/src/views/AdminHome.js
client/src/views/Landing.js
client/src/views/MediatorRegistration.js
client/src/views/Search.js
client/src/views/Settings.js
client/src/views/UserCaseShow.js
client/src/views/styles/BecomeMediatorLink.js
client/src/views/styles/HeaderH1.js

Style party 3

---

client/src/App.js
client/src/components/OutsideCourtForm.js
client/src/components/modals/AreYouSureDialog.js
client/src/components/modals/SimpleDialog.js
client/src/views/Settings.js

Small fix for netlify deploy

---

client/src/components/AdminMediatorRequestList.js
client/src/components/CourtForm.js
client/src/components/MediatorAcceptedCaseList.js
client/src/components/MediatorCard.js
client/src/components/MediatorCaseCard.js
client/src/components/MediatorCompletedCaseList.js
client/src/components/MediatorPendingCaseList.js
client/src/components/NavBar.js
client/src/components/OutsideCourtForm.js
client/src/components/UserCaseCard.js
client/src/components/modals/AcceptCaseModal.js
client/src/components/modals/CompleteCaseModal.js
client/src/components/modals/DeclineCaseModal.js
client/src/views/AuthCallback.js
client/src/views/Landing.js
client/src/views/MediatorCasesShow.js
client/src/views/MediatorCasesShow.scss
client/src/views/Search.js
client/src/views/Settings.js
client/src/views/UserCaseShow.js
client/src/views/styles/BecomeMediatorLink.js

Focused on fixing styling bugs.

Style party 4

---

client/src/components/CourtForm.js
client/src/components/DeactivateAccountButton.js
client/src/components/SendRequestButton.js
client/src/components/modals/AcceptCaseModal.js
client/src/components/modals/DeclineCaseModal.js

Add more user tracking to the app.

Expand mixpanel

---

client/src/components/DeactivateAccountButton.js
client/src/views/MediatorCasesShow.js
client/src/views/Settings.js
client/src/views/StripeCallback.js
client/src/views/styles/BecomeMediatorLink.js

Settings layout

---

client/src/views/MediatorRegistration.js

Made registration form resemble our other forms more closely. Fixed a bug associated with the multiple selection inputs. 

Form housekeeping

---

client/src/views/MediatorCasesShow.js
client/src/views/Settings.js

i added some spacing between cases tabs for mediator so that the words don't cut out when looking at the site in a small screen

Mediator tabs bug

---

client/package-lock.json
client/package.json
client/src/components/Addendum.js
client/src/views/Settings.js

Fixed timestamp on addendums popup to be a string

was able to fix timestamp on addendum popup

---

client/src/components/Addendum.js
client/src/components/AdminRequestCard.js
client/src/components/MediatorCaseCard.js
client/src/components/MediatorFilter.js
client/src/components/MediatorList.js
client/src/components/OutsideCourtForm.js
client/src/components/Pagination.js
client/src/components/Pagination.scss
client/src/components/modals/AcceptCaseModal.js
client/src/components/modals/CompleteCaseModal.js
client/src/components/modals/DeclineCaseModal.js
client/src/routes/RootRouter.js
client/src/views/Login.js
client/src/views/Search.js

Added pagination to mediatorsList and deleted some unused dependencies.
- [x ] I have performed a self-review of my own code

Pagination mediator list

---

client/src/views/UserCaseShow.js

There was a margin peeking out of the right past the nav bar making a horizontal scroll bar. Added an overflow prop of hidden.

Overflow fix cases

---

client/src/components/InvoiceForm.js
client/src/components/MediatorCaseCard.js
client/src/components/index.js
client/src/components/modals/InvoiceCaseModal.js

added form for creating an invoice

---

client/package-lock.json
client/package.json
client/public/index.html
client/src/components/AddendumInvoiceTabs.js
client/src/components/AddendumInvoiceTabs.scss
client/src/components/AddendumsList.js
client/src/components/UserCaseCard.js
client/src/components/UserCaseCard.scss
client/src/components/UserCaseList.js
client/src/components/UserInvoice.js
client/src/components/UserInvoice.scss
client/src/components/UserInvoiceList.js
client/src/components/modals/CaseOverviewDialog.js

Moved much of the functionality of UserCaseCard into a full-screen dialog accessible by clicking the view details button. We created a Case Overview page with all of the relevant case information included there.
@rogercp and @brennuck also worked on this branch via the LiveShare vs-code extension.

Case overview

---

client/package-lock.json
client/src/components/StripeButton.js
client/src/routes/TestRouter.js
client/src/routes/UsersRouter.js
client/src/views/Landing.js
client/src/views/StripeCheckout.js
client/src/views/Testing.js
client/src/views/index.js

Add a view to handle a successful Stripe Checkout.

Stripe checkout

---

client/src/views/MediatorCasesShow.js

changed url for stripe connect

changed url for stripe connect

---

client/src/views/MediatorCasesShow.js

changes the url for connecting bank accounts to the live version on stripe

updated connect url

---

client/src/routes/CasesRouter.js
client/src/views/index.js

Court Form and non Court Form Fix

fixed form routing  in index on views directory

---

client/src/views/MediatorCasesShow.js
client/src/views/MediatorRegistration.js

Fixed a couple visual problems and some typos
- [x ] I have performed a self-review of my own code

Visual housekeeping

---

client/cypress/integration/examples/create-case.spec.js
client/cypress/integration/examples/search-mediators.spec.js
client/cypress/integration/examples/user-login.spec.js
client/cypress/integration/examples/user-settings.spec.js

Expand cypress integration testing.

Cypress testing

---

client/src/views/MediatorCasesShow.js

We are going to demo the application in test mode, so the connect url had to be changed

changed url back to testing for demo

---

client/src/components/UserCaseCard.js

Added extra conditional cases for court-forms on UserCaseCard

Conditional Fix

---

client/src/components/InvoiceForm.js
client/src/components/UserInvoice.js
client/src/components/modals/CaseOverviewDialog.js

Added money signs

---

client/src/components/AddendumInvoiceTabs.js
client/src/components/CaseDocumentsList.js
client/src/components/modals/CaseOverviewDialog.js
client/src/helpers/firebase.js

Firebase Storage

---

client/src/components/AdminRequestCard.js
client/src/components/MediatorCard.js
client/src/components/UserCaseCard.js
client/src/components/styles/UserCaseCard.scss
client/src/views/MediatorRegistration.js

Remove duplicate IDs from html.

Remove duplicate IDs from html

---

client/src/views/StripeCallback.js

Fixes bug that kept mediator cases from refreshing

Connect bug

---

client/src/views/Landing.js

changed word solve into manage

changed the word solve to manage

---

client/src/components/UserCaseCard.js

brought back ribbon styling

---

client/src/components/AdminRequestCard.js
client/src/components/InvoiceForm.js
client/src/components/MediatorCaseCard.js
client/src/components/SideNavBlock.js
client/src/components/UserInvoice.js
client/src/views/Landing.js
client/src/views/Login.js
client/src/views/NoMatch.js
client/src/views/OutsideCourtForm.js

In order to make the login flow for firebase authentication a little smoother, I used a modal pop-up and made the adjustments to get that working with firebase, rather than redirecting to a new, mostly blank page.
Also got rid of some of the warnings in console from various files.

Victor goico

---

client/src/components/NavBar.js
client/src/components/styles/_navbar.js
client/src/routes/UsersRouter.js
client/src/views/Messaging.js
client/src/views/index.js

Added a view and a route for messaging

Set up a route and a vew for messaging

---

client/src/components/NavBar.js
client/src/components/styles/_navbar.js
client/src/helpers/firebase.js
client/src/routes/UsersRouter.js
client/src/views/Messaging.js
client/src/views/Settings.js
client/src/views/index.js
client/src/views/styles/_settings.js

Implemented image uploads for the user profile and added styling for settings view mobile view

Profile img upload
